#!/usr/bin/env bash
USERNAME=volgactf
IMAGE=volgactf-final-python-checker

version=`cat BASE-VERSION`
echo "version: $version"

docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$version
docker push $USERNAME/$IMAGE:latest
docker push $USERNAME/$IMAGE:$version
